### ISSUE TITLE
🐳 [V1.2 CRITICAL] Docker Infrastructure Setup

### ISSUE THREAD

**Issue by gr3enarr0w** [gr3enarr0w/star-wars-rpg-character-manager#102]
## Production Deployment Infrastructure

**Priority**: CRITICAL - Launch Blocker
**Requirement**: Dockerized deployment for v1.2

### Missing Components
- [ ] `Dockerfile` with multi-stage build
- [ ] `docker-compose.yml` with full stack
- [ ] `nginx.conf` for reverse proxy
- [ ] Production WSGI server (Gunicorn)
- [ ] Health check endpoints
- [ ] Container security configuration

### Required Stack
```yaml
Services:
  - app: Flask app with Gunicorn
  - mongodb: MongoDB with auth
  - nginx: SSL termination + reverse proxy
  - volumes: Data persistence

Configuration:
  - Non-root user in container
  - Health checks for all services
  - Restart policies
  - Environment variable injection
  - Log volume mounting
```

### Dockerfile Requirements
```dockerfile
FROM python:3.13-slim
# Multi-stage build for optimization
# Non-root user for security
# Health check integration
# Gunicorn production server
```

### docker-compose.yml Features
- Production MongoDB with authentication
- Nginx reverse proxy with SSL
- Application container with health checks
- Data volume persistence
- Environment variable management
- Network isolation

### Acceptance Criteria
- [ ] Complete Docker stack builds successfully
- [ ] `docker-compose up` starts all services
- [ ] Application accessible via nginx
- [ ] MongoDB data persists across restarts
- [ ] Health checks working for all containers
- [ ] SSL/HTTPS properly configured
- [ ] Production-ready Gunicorn configuration

**Target Completion**: Week 1
**Dependencies**: Production auth system (#101)
