### ISSUE TITLE
[ENHANCEMENT] Implement pre-commit hooks for secret detection

### ISSUE THREAD

**Issue by gr3enarr0w** [gr3enarr0w/star-wars-rpg-character-manager#36]
**Priority:** High
**Category:** Security
**Target Version:** v1.0

## Enhancement Description
Implement pre-commit hooks to prevent accidental commit of secrets, API keys, and sensitive data to the repository.

## Problem Statement
Despite improved .gitignore and security practices, there's still risk of:
- Accidentally committing secrets in new files
- Developers bypassing .gitignore rules
- Secrets hidden in configuration files
- Test data containing real credentials

## Proposed Solution
Implement comprehensive pre-commit hook system with multiple security checks:

### Pre-commit Hook Features
- **Secret pattern detection** (API keys, passwords, tokens)
- **File extension validation** (prevent .env, .key files)
- **Content scanning** for common secret patterns
- **Custom rule configuration** for project-specific patterns
- **Integration with 1Password CLI** for secret validation

### Security Checks
1. **Pattern-based detection**:
   - API key patterns (various formats)
   - JWT tokens
   - Database connection strings with credentials
   - Common password patterns
   - Private keys (PEM, SSH, etc.)

2. **File-based checks**:
   - Prevent .env files (except .env.example)
   - Block .key, .pem, .p12 files
   - Scan configuration files
   - Check for backup files with secrets

3. **Content analysis**:
   - Entropy analysis for random strings
   - Base64 encoded content detection
   - Common secret variable names
   - Hardcoded IP addresses and URLs

### Phase 1: Basic Hook Setup
1. **Install pre-commit framework**
2. **Configure standard hooks** (trailing whitespace, large files)
3. **Add secret detection hooks** (detect-secrets, git-secrets)
4. **Custom pattern rules** for the project

### Phase 2: Advanced Features
1. **1Password integration** for secret validation
2. **Custom secret patterns** specific to Star Wars RPG Manager
3. **Whitelist management** for false positives
4. **Team configuration** sharing

### Tools and Dependencies
- **pre-commit framework**
- **detect-secrets** for secret pattern detection
- **git-secrets** for additional pattern matching
- **custom Python hooks** for project-specific checks
- **1Password CLI integration**

### Configuration Files
```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      
  - repo: https://github.com/Yelp/detect-secrets
    hooks:
      - id: detect-secrets
        
  - repo: local
    hooks:
      - id: star-wars-rpg-secrets
        name: Star Wars RPG secret detection
        entry: ./scripts/check-secrets.py
```

### Custom Rules
- MongoDB connection strings with credentials
- JWT tokens with "Bearer" prefix
- Flask secret keys
- OAuth client secrets
- Encryption passwords and salts

## User Value
- **Prevent Security Incidents**: Stop secrets before they reach repository
- **Developer Education**: Immediate feedback on security practices
- **Compliance**: Meet security requirements automatically
- **Peace of Mind**: Automated protection against human error

## Acceptance Criteria
- [ ] Pre-commit hooks installed and configured
- [ ] Secret detection working for all common patterns
- [ ] Custom rules for Star Wars RPG Manager implemented
- [ ] Team setup documentation created
- [ ] CI/CD integration for backup protection
- [ ] Whitelist management for false positives
- [ ] Developer onboarding includes hook setup
- [ ] Hook bypass procedures documented for emergencies

### Setup Scripts
- **Developer setup script**: Automatic hook installation
- **CI/CD validation**: Server-side enforcement
- **Update mechanism**: Hook configuration updates

### Performance Considerations
- **Fast execution**: Hooks complete in under 5 seconds
- **Incremental scanning**: Only check modified files
- **Caching**: Avoid rescanning unchanged content

## Documentation Requirements
- Setup guide for new developers
- Troubleshooting common hook issues
- Adding custom patterns
- Managing false positives
- Emergency bypass procedures

## Related Issues
- Prevents issues found in security audit
- Complements Issue #34 (1Password integration)
- Supports Issue #35 (secret rotation) by preventing manual commits
